//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playground.Wpf.Cui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Playground.Wpf.Cui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerID;CompanyName;ContactName;ContactTitle;Address;City;Region;PostalCode;Country;Phone;Fax
        ///ALFKI;Alfreds Futterkiste;Maria Anders;Sales Representative;Obere Str. 57;Berlin;NULL;12209;Germany;030-0074321;030-0076545
        ///ANATR;Ana Trujillo Emparedados y helados;Ana Trujillo;Owner;Avda. de la Constitucin 2222;Mxico D.F.;NULL;05021;Mexico;(5) 555-4729;(5) 555-3745
        ///ANTON;Antonio Moreno Taquera;Antonio Moreno;Owner;Mataderos  2312;Mxico D.F.;NULL;05023;Mexico;(5) 555-3932;NULL
        ///AROUT;Around the Horn;Thomas H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductID;ProductName;SupplierID;CategoryID;QuantityPerUnit;UnitPrice;UnitsInStock;UnitsOnOrder;ReorderLevel;Discontinued
        ///1,&quot;Chai&quot;,1,1,&quot;10 boxes x 20 bags&quot;,18,39,0,10,0
        ///2,&quot;Chang&quot;,1,1,&quot;24 - 12 oz bottles&quot;,19,17,40,25,0
        ///3,&quot;Aniseed Syrup&quot;,1,2,&quot;12 - 550 ml bottles&quot;,10,13,70,25,0
        ///4,&quot;Chef Anton&apos;s Cajun Seasoning&quot;,2,2,&quot;48 - 6 oz jars&quot;,22,53,0,0,0
        ///5,&quot;Chef Anton&apos;s Gumbo Mix&quot;,2,2,&quot;36 boxes&quot;,21.35,0,0,0,1
        ///6,&quot;Grandma&apos;s Boysenberry Spread&quot;,3,2,&quot;12 - 8 oz jars&quot;,25,120,0,25,0
        ///7,&quot;Uncle Bob&apos;s Organic Dried Pears&quot;,3,7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
    }
}
