<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">True</GeneratePackageOnBuild>
	</PropertyGroup>
	<PropertyGroup>
		<Version>5.0.1</Version>
		<AssemblyVersion>5.0.1</AssemblyVersion>
		<FileVersion>5.0.1</FileVersion>
	</PropertyGroup>
	<PropertyGroup>
		<Product>BytecodeApi.Wpf.Cui</Product>
		<Title>BytecodeApi.Wpf.Cui</Title>
		<Description>Bytecode77 WPF common UI.</Description>
		<Company>bytecode77</Company>
		<Authors>Martin Fischer</Authors>
		<Copyright>© bytecode77, 2026.</Copyright>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>BytecodeApi.Wpf.Cui</PackageId>
		<PackageTags>wpf controls cui vs2022 visual studio</PackageTags>
		<PackageProjectUrl>https://bytecode77.com/bytecode-api-cui</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/bytecode77/bytecode-api</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>.nuget\README.md</PackageReadmeFile>
		<PackageIcon>.nuget\PackageIcon.png</PackageIcon>
		<PackageOutputPath>../$Build</PackageOutputPath>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="SharpVectors" Version="1.8.5" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\BytecodeApi\BytecodeApi.csproj" />
		<ProjectReference Include="..\BytecodeApi.Wpf\BytecodeApi.Wpf.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include=".nuget\README.md" Pack="true" PackagePath=".nuget\" />
		<None Include="..\.nuget\PackageIcon.png" Link=".nuget\PackageIcon.png" Pack="true" PackagePath=".nuget\" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Resources\Icons\**\*.svg" />
		<Resource Include="Resources\Icons\**\*.svg" />
	</ItemGroup>
</Project>