//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN RSA PRIVATE KEY-----
        ///MIIEowIBAAKCAQEAo9P/gKwKxmuLSHsPANe6npeKmq56EB4CdQwD0qbqLm44aySD
        ///XSfC04hhOZlOenD3muChXkKQeuhP3A6y+qGsznGep0oIyuNyqaw5fAxXo6KDaGT3
        ///UMhqsARhPQQLxA/WroFpV3eQIbyMZlB+OM3/kqj8fWWk+bfQ+sslNweOt1MzjNGX
        ///Ak+8IFPRAWc/IcBOpMH3Td+hefcIeeL8PrXojF2AfUs7Vxr9JmkLziwioHt/r5S8
        ///syAjqeVvckalPCv6kqNnR4xwnw3CtTR6K0zc/7pJ63rSrH8s10/CeIBeVAt0iuNZ
        ///X4tD5LWoZbF75O4KSCXNSgkTvYOm7+r8oHmFtQIDAQABAoIBACK25loemn3nBfGK
        ///2egEzm+SjvUt6YGGymCA9kJpyg+inWPerdNMfJUUPf3VhXKeg2kXFjqCAll45osr
        ///tjMzlQl9u++Y2Xocb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RSAPrivateKey {
            get {
                return ResourceManager.GetString("RSAPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PUBLIC KEY-----
        ///MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo9P/gKwKxmuLSHsPANe6
        ///npeKmq56EB4CdQwD0qbqLm44aySDXSfC04hhOZlOenD3muChXkKQeuhP3A6y+qGs
        ///znGep0oIyuNyqaw5fAxXo6KDaGT3UMhqsARhPQQLxA/WroFpV3eQIbyMZlB+OM3/
        ///kqj8fWWk+bfQ+sslNweOt1MzjNGXAk+8IFPRAWc/IcBOpMH3Td+hefcIeeL8PrXo
        ///jF2AfUs7Vxr9JmkLziwioHt/r5S8syAjqeVvckalPCv6kqNnR4xwnw3CtTR6K0zc
        ////7pJ63rSrH8s10/CeIBeVAt0iuNZX4tD5LWoZbF75O4KSCXNSgkTvYOm7+r8oHmF
        ///tQIDAQAB
        ///-----END PUBLIC KEY-----.
        /// </summary>
        internal static string RSAPublicKey {
            get {
                return ResourceManager.GetString("RSAPublicKey", resourceCulture);
            }
        }
    }
}
